import type { Metadata } from "next";
import "./globals.css";

import StyledComponentsRegistry from "@/lib/registry";

export const metadata: Metadata = {
  title: "Armarinho Sistema",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
