import type { Metadata } from "next";
import "./globals.css";

import StyledComponentsRegistry from "@/lib/registry";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "../services/queryClient";
import { AuthProvider } from "@/context/authContext";

export const metadata: Metadata = {
  title: "Armarinho Sistema",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
